### ISSUE TITLE
bufbuild/validate-go: managed mode breaks import path

### ISSUE THREAD

**Issue by gnuletik** [bufbuild/plugins#356]
When using [buf's managed mode](https://docs.buf.build/tour/use-managed-mode) with the [validate-go plugin](https://buf.build/bufbuild/validate-go), the `envoyproxy/protoc-gen-validate` URL is override with an invalid local path.

Reproduction:

```proto
// test.proto

syntax = "proto3";

package examplepb;

import "validate/validate.proto";

// option go_package = "example.com/protopb";

message Person {
  uint64 id = 1 [(validate.rules).uint64.gt = 999];
}
```

```yaml
# buf.yaml

version: v1
deps:
  - buf.build/envoyproxy/protoc-gen-validate
```

```yaml
# buf.gen.yaml

version: v1
managed:
  enabled: true
  go_package_prefix:
    default: example.com/protopb
plugins:
  - plugin: buf.build/protocolbuffers/go:v1.28.1
    out: gen/go
    opt: paths=source_relative

  - plugin: buf.build/grpc/go:v1.2.0
    out: gen/go
    opt: paths=source_relative

  - plugin: buf.build/bufbuild/validate-go:v0.9.0
    out: gen/go
    opt: paths=source_relative
```

```
$ buf generate # works as expected

# here's the issue
$ go test ./...
gen/go/test.pb.go:10:2: no required module provides package example.com/protopb/validate; to add it:
	go get example.com/protopb/validate
```

That's because the `gen/go/test.pb.go` file has the following import:

```go
package protob

import (
	_ "example.com/protopb/validate" // this package does not exists
       // other imports...
)
```

When commenting the `managed` section inside `buf.gen.yaml` and uncommenting the `go_package` line in `test.proto`, it works as expected.

```go
package protopb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
       // other imports...
)
```
