### ISSUE TITLE
Plugin request for Buf Schema Registry: protoc-gen-prost-crate

### ISSUE THREAD

**Issue by cobbinma** [bufbuild/plugins#608]
Rust plugins were previously added to this repository [here](https://github.com/bufbuild/plugins/issues/96) but protoc-gen-prost-crate was not.

Can protoc-gen-prost-crate be added so that we can move away from using remote generation alpha.

We are currently using the remote plugin with `no_features` to generate a `mod.rs` file in the output directory and a static `Cargo.toml`.

```yaml
  - remote: buf.build/prost/plugins/crate:v0.3.1-1
    out: autogen/lang/rust
    opt:
      - no_features
```

## Mandatory

**Where is the source code for the plugin?**

https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-prost-crate

## Optional

**Does the plugin have a valid semver version?**

https://github.com/neoeinstein/protoc-gen-prost/releases/tag/protoc-gen-prost-crate-v0.2.0

**Does the plugin have a dependency on another plugin?**

https://buf.build/community/neoeinstein-prost
