### ISSUE TITLE
Unclear how to set `csharp_namespace`

### ISSUE THREAD

**Issue by q42jaap** [bufbuild/plugins#983]
In my buf.gen.csharp.yaml file I want to set csharp_namespace. I've found that I can set `override` in the yaml file, but the plugin warns about the override not being used (I have no idea what the key should be).
I actually want something like `go_package_prefix.default`, but that's not a thing in `csharp_namespace`.

I also tried `option csharp_namespace = "My.Service.View.V1";` in the `.proto` files but that doesn't work either.

**Comment by q42jaap** [comment]
I noticed that with protoc --csharp_out `option csharp_namespace` in the `.proto` file works, but with the `bufbuild/grpc/csharp:v1.60.0 and buf.build/protocolbuffers/csharp` I can't get `option csharp_namespace` to do anything.

**Comment by doriable** [comment]
To address the first concern around `buf.gen.chsarp.yaml`: yes, so you would set the following:

```
version: v1
managed:
  enabled: true
  csharp_namespace
```

And then yes, as you pointed out, you can only set `override` or `except`. Unfortunately we do not currently offer a `prefix` style setting, similar to `go_package`.

If you are using remote plugins with `buf generate` and you would like to use the options you've set in the proto file instead of managed mode, ensure that managed mode is not enabled:

```
version: v1
managed:
  enabled: false
```

**Comment by q42jaap** [comment]
I could not get the `override` to do anything, are there examples of how this works?

**Comment by doriable** [comment]
> I could not get the `override` to do anything, are there examples of how this works?

Here would be an example of the namespace override:

```
version: v1
managed:
  enabled: true
  csharp_namespace:
    override:
      buf.build/googleapis/googleapis: foo
plugins:
  - plugin: buf.build/grpc/csharp
    out: gen
  - plugin: buf.build/protocolbuffers/csharp
    out: gen
```

Something to note about the `override` -- you cannot set an override for your current module. I think this is the issue you are running into. If this is the use-case, then I believe the best workaround right now is to set file option. Sorry for the inconvenience!
